### ISSUE TITLE
[BE] ~/town API 개발

### ISSUE THREAD

**Issue by jonghopark95** [woowa-techcamp-2021/deal-7#21]
## :hammer: 기능 설명

내 위치 API 리스트를 개발합니다.

## 📑 체크리스트

> 수행해야 할 체크리스트

- [x] POST ~/town
  - 내 동네 설정하기 슬라이드에서, 현재 위치 입력 후 확인 시 요청
  - 이미 user.town.length === 2 이면 Bad Request
  - town 길이는 8글자 까지 
    - 추후에 변경될 수 있으므로 상수로 빼놓기
  - body : { town : "역삼동" }

- [x] PUT ~/town
  - 내 동네 설정하기 슬라이드에서 동네를 지우기 위해 요청
  - 유저 town에 없는 값이 Body 에 들어올 경우 Bad Request
  - body에는 지우려는 town 넣어서 요청
    - e.g. body : { town : "역삼동" }

## 🚧 주의 사항

> 기능을 구현할 때 유의깊게 살펴볼 사항

- X

**Comment by crongro** [comment]
이슈리스트가 꼼꼼하게 많네요.
